// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

namespace UpnpServer.Configurations;
public class AppSettings
{
    public required string Urls { get; init; }
    public required UPnPServerConfiguration UPnPServer { get; init; }
    public class UPnPServerConfiguration
    {
        public required int RefreshIntervalSeconds { get; init; }
        public required bool Enabled { get; init; }
        public class PortsItem
        {
            public required string Description { get; init; }
            public required int PrivatePort { get; init; }
            public required int PublicPort { get; init; }
            public required string Protocol { get; init; }
        }

        public required List<PortsItem> Ports { get; init; }
    }

    public required CloudflareConfiguration Cloudflare { get; init; }
    public class CloudflareConfiguration
    {
        public required string BaseUrl { get; init; }
        public required string BearerToken { get; init; }
        public required int RefreshIntervalSeconds { get; init; }
        public required bool Enabled { get; init; }
        public required string ZoneId { get; init; }
        public class RecordsItem
        {
            public required string Name { get; init; }
            public required string Type { get; init; }
            public required int TTL { get; init; }
            public required bool Proxied { get; init; }
        }

        public required List<RecordsItem> Records { get; init; }
    }

}

